@NewReservationApi_HostAddress = https://localhost:7189
@BearerToken = Bearer CfDJ8CRokUk55g9PjEetJzAoBRIICP1bUuLEoa_ijjcYzj3NaurT9pQAQmedojDw5570F-RvRtcg_8Te0fIYNgoKJ8RvoQdCyiYqPYDchpZIuiCw0FSOiFAXQm70nPRwrZIXAYLsWV_nxvO75BZXN-oMwAXjlq4ntt-qREctuWq3l8CjZz_aJ8qEOyxstBK8IhifTYnIXVZzHYe46WbMBQ2jmplxqFpqO3_xyDmSSwQM80h6X3v93oUygnWfW4lkweBuffbPnN-GLe4iYzrAKC0N38dt3cZFxirET_MhYYUw4F-xbmWkDAJ_QIlRhVeLe066GEl4UaAkeUImPLjiDwLpFiPgXUo336TODS305tWq_UEdysXoO9YihpAptG-7eED72JCkxHE-os8rPAFgjjTxBd1AK6kip2waWKi2auzgV8nEtET9QLFT1czdoEVrshyN1Qskl1c-Qbj5z09XsNC0rDRaOhbOFWL9VokA8PJ-x-JZ2qIKpROEmsTogKR89VkX-eF0KTQ2TDE8mW2HEYBTDIF01CFdXQfh4MEF8HafkbYLAC5UpGoVAgOxNrzEALy_VcyDh85l7VhA5-XoNscEprYBoVuwM7Hf-7emyQvQ9N0nBMZikgh71rN4lpiX3EIAzVdfWVjwtc7Cf_Iwdq4X_GVgXZOyo86PuVeSH8JBanaxDihHgpCPTF-Wiz3r0PW4vKnc2fFCOUYC4TbT42t2y5c

###

GET  {{NewReservationApi_HostAddress}}/reservations
Authorization: {{BearerToken}}
Accept: application/json



